### ISSUE TITLE
The wallet can not be compiled in ubuntu, it has an error

### ISSUE THREAD

**Issue by ghost** [vcoin-z/virtualcoin#3]
I have installed the following dependencies
Sudo apt-get install build-essential
Sudo apt-get install libssl-dev
Sudo apt-get install libdb4.8-dev
Sudo apt-get install libdb4.8 ++ - dev
  Boost 1.40+: sudo apt-get install libboost-all-dev
Sudo apt-get install libqrencode-dev

But still the compilation does not work, presenting the following error

protocol.h:23:3: error: expected primary-expression before ‘==’ token
 =======
   ^
protocol.h:23:5: error: expected primary-expression before ‘==’ token
 =======
     ^
protocol.h:23:7: error: expected primary-expression before ‘=’ token
 =======
       ^
protocol.h:24:5: error: expected primary-expression before ‘return’
     return testnet ? 443 : 80;
     ^
protocol.h:25:1: error: expected primary-expression before ‘>>’ token
 >>>>>>> origin/9.2.0
 ^
protocol.h:25:3: error: expected primary-expression before ‘>>’ token
 >>>>>>> origin/9.2.0
   ^
protocol.h:25:5: error: expected primary-expression before ‘>>’ token
 >>>>>>> origin/9.2.0
     ^
protocol.h:25:7: error: expected primary-expression before ‘>’ token
 >>>>>>> origin/9.2.0
       ^
protocol.h:25:9: error: ‘origin’ was not declared in this scope
 >>>>>>> origin/9.2.0
         ^
protocol.h:26:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
alert.cpp: In member function ‘bool CAlert::AppliesToMe() const’:
alert.cpp:124:70: error: ‘CLIENT_VERSION’ was not declared in this scope
     return AppliesTo(PROTOCOL_VERSION, FormatSubVersion(CLIENT_NAME, CLIENT_VERSION, std::vector<std::string>()));
                                                                      ^
makefile.unix:193: recipe for target 'obj/alert.o' failed
make: *** [obj/alert.o] Error 1

**Comment by bumbacoin** [comment]
try deleting lines 23 - 25
https://github.com/vcoin-z/virtualcoin/blob/9.2.0/src/protocol.h#L23

but you'll end up with similar errors popping up a few more times i suspect.

if you want to bang your head against it, just keep deleting the sections (similar to those i just mentioned) in each file that has errors

**Comment by bumbacoin** [comment]
whoever coded this is didnt compile it without major edits.

**Comment by ghost** [comment]
What I want is to build the daemon in ubuntu 16.04, but it has been impossible to compile the daemon in linux, it is not qt installation, I am new to linux, so I am not a programmer, so I ask for help. And before I have compiled other currencies and I have not had these problems, I appreciate your patience, and I look forward to your answers thanks

**Comment by bumbacoin** [comment]
for lack of any other way of putting it, the problem seems that there is historical data kept in the code(?)

eg
<<<<<<< HEAD
    return testnet ? 80 : 443;
=======
    return testnet ? 443 : 80;
>>>>>>> origin/9.2.0
}

above the HEAD section is assumedly the current version, so I built the coind by going through, and every time it gave me an error, finding the similar section in each file, then deleting the non-head section.

here's the above code with stuff i deleted, commented out 

// <<<<<<< HEAD
    return testnet ? 80 : 443;
//=======
//    return testnet ? 443 : 80;
//>>>>>>> origin/9.2.0

the necessary code is only the section between "<<<<HEAD" and "======"
ie
    return testnet ? 80 : 443;

}


but, apparently a re-release is in order for tomorrow, so maybe the code will be cleaner,
also you'll need a working leveldb folder from another source as well.

**Comment by ghost** [comment]
bumbacoin, Excuse me, in what files exactly do you have to remove those lines that you have named to build the demon?

**Comment by bumbacoin** [comment]
have a look at this search.
there are a few files that are un-necessary for compiling, but i think that's probably all i changed.
i did it by compiling, and every time it stopped with an error, i cleaned the file that was a problem.

https://github.com/vcoin-z/virtualcoin/search?p=2&q=origin%2F9.2.0&utf8=✓



however you might notice the version in thread is now 14.0.2
i'm assuming the dev is not updating this code base in a new effort to disguise the pre-mine.

of course i could be wrong.

**Comment by ghost** [comment]
bumbacoin,  Hi, should i leave the files as they look on the link? Or should we erase something? Pardon my ignorance. Is the link in the link edited?

**Comment by bumbacoin** [comment]
see if this helps. http://pastebin.com/NubBdEem

basically you need to delete all the code that confuses, or doubles up on defining variable values.


please note, **until dev updates this code will not connect to network at the moment,** 
at least a version change is probable
https://github.com/vcoin-z/virtualcoin/blob/9.2.0/src/version.h

but i'm unsure if any other code is changed.

**Comment by ghost** [comment]
Comment the part of the files where it appears
>>>>>>> origin / 9.2.0

As follows:
// >>>>>>> origin / 9.2.0

But I have doubts about three files
1.
Src / addrman.h

  // Move an entry from the "new" table (s) to the "tried" table
219 // @pre vvUnkown [nOrigin] .count (nId)! = 0
220 void MakeTried (CAddrInfo & info, int nId, int nOrigin);
221
222 // Mark an entry "good", possibly moving it from "new" to "tried".

Should I comment this way ?:

  // Move an entry from the "new" table (s) to the "tried" table
219 // @pre vvUnkown [nOrigin] .count (nId)! = 0
220 // void MakeTried (CAddrInfo & info, int nId, int nOrigin);
221
222 // Mark an entry "good", possibly moving it from "new" to "tried".

2.
Contrib / gitian-descriptors / osx / gitian-osx-native.yml

  ./configure --prefix = $ {NATIVEPREFIX} --target = $ {HOST} CFLAGS = "$ {CFLAGS} -I $ {NATIVEPREFIX} / include -D__DARWIN_UNIX03 -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS" LDFLAGS = "$ {LDFLAGS} -Wl , -rpath = \\\ $ \ $ ORIGIN /../ lib "--with-sysroot = $ {SDK}


Should I comment the whole code as well?

// $ / CFLAGS} -I $ {NATIVEPREFIX} / include -D__DARWIN_UNIX03 -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS "LDFLAGS =" $ {LDFLAGS} -Wl, -rpath = \\\ $ \ $ ORIGIN /../ lib "--with-sysroot = $ {SDK}

3.
Src / addrman.cpp

Void CAddrMan :: MakeTried (CAddrInfo & info, int nId, int nOrigin)
205 {
206 assert (vvNew [nOrigin] .count (nId) == 1);
207
208 // remove the entry from all new buckets
...
252 vvNew [nOrigin] .insert (vTried [nPos]);
253}
254 nNew ++;
255
256 vTried [nPos] = nId;
257 // we just overwrote an entry in vTried; No need to update nTried


Should comment all that code from:

// void CAddrMan :: MakeTried (CAddrInfo & info, int nId, int nOrigin)
205 // {
206 // assert (vvNew [nOrigin] .count (nId) == 1);
207
208 // remove the entry from all new buckets
...
252 vvNew [nOrigin] .insert (vTried [nPos]);
253 //}
254 // nNew ++;
255
256 // vTried [nPos] = nId;
257 // we just overwrote an entry in vTried; No need to update nTried

4. also delete the folder leveldb and change it by another, from arcticcoin

Try to compialar but I still leave error, could you send me the arcivos you modified? Is that I'm new to linux and I do not understand this well

My email is teosanru@gmail.com

**Comment by ghost** [comment]
**Do everything you told me but look now it appears this error:**

D -MF obj / checkpoints.d -o obj / checkpoints.o checkpoints.cpp
Checkpoints.cpp: 49: 91: warning: left operand of comma operator has no effect [-Wunused-value]
         (0, uint256 ("0x00000496d303ae6e6ed9d474639f18b3fdf70166c8d89d1267bbf5fd640e1690"))
                                                                                           ^
Checkpoints.cpp: 50: 92: error: no match for call to '(uint256) (int, uint256)'
         (1, uint256 ("0x000000298e2128eec401430714db3f2307cca97095515b7db6fc1e1bd21b3268"))
                                                                                            ^
Checkpoints.cpp: 53: 9: error: expected '}' before ';' Token
         ;
         ^
Checkpoints.cpp: 54: 34: error: redefinition of 'const Checkpoints :: CCheckpointData Checkpoints :: data'
     Static const CCheckpointData data = {
                                  ^
Checkpoints.cpp: 44: 34: error: 'const Checkpoints :: CCheckpointData Checkpoints :: data' previously declared here
     Static const CCheckpointData data = {
                                  ^
Make: *** [obj / checkpoints.o] Error 1

**Comment by bumbacoin** [comment]
sounds like you might have accidentally deleted a ) } ;
or something.

**Comment by ghost** [comment]
As I told you before, do not delete any more code that was repeated, that you indicated to me, and all
>>>>>>> origin / 9.2.0
=======
<<<<<<< HEAD

I did everything you told me but gave me the same error

0 -DUSE_IPV6=1 -I/root/virtualcoin/src/leveldb/include -I/root/virtualcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/checkpoints.d -o obj/checkpoints.o checkpoints.cpp
checkpoints.cpp:47:91: warning: left operand of comma operator has no effect [-Wunused-value]
         (  0, uint256("0x00000496d303ae6e6ed9d474639f18b3fdf70166c8d89d1267bbf5fd640e1690"))
                                                                                           ^
checkpoints.cpp:48:92: error: no match for call to '(uint256) (int, uint256)'
         (  1, uint256("0x000000298e2128eec401430714db3f2307cca97095515b7db6fc1e1bd21b3268"))
                                                                                            ^
checkpoints.cpp:51:9: error: expected '}' before ';' token
         ;
         ^
checkpoints.cpp:52:34: error: redefinition of 'const Checkpoints::CCheckpointData Checkpoints::data'
     static const CCheckpointData data = {
                                  ^
checkpoints.cpp:43:34: error: 'const Checkpoints::CCheckpointData Checkpoints::data' previously declared here
     static const CCheckpointData data = {
                                  ^
make: *** [obj/checkpoints.o] Error 1
root@u19757984:~/virtualcoin/src# 

The problem I think is in the checkpoints.cpp file
Could you send it as you have it?

**Comment by bumbacoin** [comment]
looks like code has been updated, try starting again with a fresh download

**Comment by ghost** [comment]
Thank you. It looks like if the code was cleaned

2017-02-04 1:53 GMT-05:00 bumbacoin <notifications@github.com>:

**Comment by ghost** [comment]
Still has installation errors

/root/virtualcoin/src/leveldb.cpp:76: undefined reference to `leveldb::Status::ToString() const'
collect2: error: ld returned 1 exit status
make: *** [virtualcoind] Error 1

**Comment by bumbacoin** [comment]
yah. same as this issue
https://github.com/vcoin-z/virtualcoin/issues/2

you'll need to copy a working leveldb folder from another coin,

**Comment by ghost** [comment]
I remove the virtualcoin leveldb folder, and can I replace it with any other currency other than an x11 algorithm?

**Comment by bumbacoin** [comment]
any currency. not just x-11
it is only a database for wallet and nothing to do with algorithm of coin.

here's ours :)
https://github.com/bumbacoin/bumbacoin2-test

**Comment by ghost** [comment]
One question, the virtualcoin reward is 100 coins per block until you reach block 1000? Also according to law in the twiter thread the value of each virtualcoin are 100.00 usd, but I do not see any exchange, it is more I saw on the internet the value of $ 0.003303, you know where they can sell at the price that the dev said?

**Comment by bumbacoin** [comment]
the block reward is based on difficulty, so at the moment with the diff so high and under block 1000 the reward is 100.
also coinmarketcap refers to yobit which is on one of the older dead chains, and their wallet is in maintenance anyway.

and except
the dev has over 387 million (mined in block 11) of them so i doubt they're really worth any where near that much.

**Comment by ghost** [comment]
But you know in which exchange has that value of 100 usd the virtualcoins?


2017-02-04 8:16 GMT-05:00 bumbacoin <notifications@github.com>:

**Comment by bumbacoin** [comment]
lol.
dude.
sorry but no-where will VC ever reach $100 USD.
please do not get robbed.

**Comment by ghost** [comment]
When you say this
(And except
The dev has over 387 million (mined in block 11) of them so i doubt they're
really worth any where near that much.

What do you mean? I did not understand very well, or rather I do not know
if I misunderstand, what is not worth it? Now according to the dev
announcement in twiter the price of each vc = 100 usd, is this correct or
am I misunderstanding? Because in this thread:
https://bitcointalk.org/index.php?topic=1775186.0 the da understand that
5000 vc = 50 BTC bone 10 usd = 1 VC

I'm sorry I want to be but I'm wrong, so far I've managed to mine 10
blocks, that means I'll have 1000's, right?

2017-02-04 11:14 GMT-05:00 bumbacoin <notifications@github.com>:

**Comment by ghost** [comment]
Look at the ad
Https://twitter.com/PayTM_/status/827697763513020417
Where the dev says that do not sell the vc to less than 100 usd each

2017-02-04 11:16 GMT-05:00 teodomiro sanchez <teosanru@gmail.com>:

**Comment by bumbacoin** [comment]
Dev tell you many good stories.
:(

**Comment by ghost** [comment]
Hahaha you mean it's fake Is not true the dev publication?
Clarify I want to know if it is really worth the virtualcoin mining?

2017-02-04 11:18 GMT-05:00 bumbacoin <notifications@github.com>:

**Comment by bumbacoin** [comment]
Dev has mined 387,420,489 coins in block 11
he would like to sell for $100 usd, but who will buy them?

with a bit of magic, he will make people buy them for 0.00003 $
and get 11,622 $

i think it is fake :)

**Comment by ghost** [comment]
Ah, you have made me sad, you have broken my illusions, lol

2017-02-04 11:28 GMT-05:00 bumbacoin <notifications@github.com>:
